#!/data/data/com.termux/files/usr/bin/bash
# Emmanuel Mahuni (c) 2018 MIT
#

rm -fv $PREFIX/bin/svdrun && rm -fv $PREFIX/bin/svdstop && rm -fv $PREFIX/bin/svcreate && rm -fv $PREFIX/bin/svact && rm -fv $PREFIX/bin/svdeact && rm -fv $PREFIX/bin/svstop && rm -fv $PREFIX/bin/svrun && rm -fv $PREFIX/bin/svstop && rm -fv $PREFIX/bin/svdrop && rm -fv $PREFIX/bin/svlist && rm -fv $PREFIX/bin/svwup && rm -fv $PREFIX/bin/svwdown


if [ $? == 0 ]; then echo; echo "uninstallation complete!"; else echo; echo "failed to uninstall!"; fi
