#!/data/data/com.termux/files/usr/bin/bash
# Emmanuel Mahuni (c) 2018 MIT
#

rf -fv $PREFIX/bin/svdrun && rf -fv $PREFIX/bin/svdstop && rf -fv $PREFIX/bin/svcreate && rf -fv $PREFIX/bin/svact && rf -fv $PREFIX/bin/svdeact && rf -fv $PREFIX/bin/svstop && rf -fv $PREFIX/bin/svrun && rf -fv $PREFIX/bin/svstop && rf -fv $PREFIX/bin/svdrop && rf -fv $PREFIX/bin/svlist && rf -fv $PREFIX/bin/svwup && rf -fv $PREFIX/bin/svwdown


if [ $? == 0 ]; then echo "uninstallation complete!"; else echo "failed to uninstall!"; fi
