#!/data/data/com.termux/files/usr/bin/bash
echo 'Cleaning up after test_sv service...'
# do any preliminaries here, setting of paths ports etc

if [ $fg ]; then
    # do something in the foreground
		echo 'wip finish script foreground mode'
else
    # do something in the background
		echo 'wip finish script background mode' >/dev/null 2>&1
fi

