#!/data/data/com.termux/files/usr/bin/bash
echo 'Starting test_sv service...'
# do any preliminaries here, setting of paths ports etc
if [ -z $sleeping ]; then export sleeping=100; fi

if [ $fg ]; then
    # run command in the foreground, this is mainly there for testing purposes, when troubleshooting service
    # use fg=1 runsv /path/to/this/service/dir
    # then see if there are any errors or issues when the command runs, this enables you to debug the service
    # nb: the foreground and background commands should be identical except for the redirection. so whatever
    #     changes you do when troubleshooting, reflect them on the background service as well since it is the
    #     default that is run by services admin.
    exec sleep $sleeping
else
    # run command in the background, this is the actual expected behaviour of services and the default command
    # that is ran by services admin.
    exec sleep $sleeping >/dev/null 2>&1
fi

